== CA SV As Code

This project provides simple **Java annotations** that can be used  in your Junit Test to deploy Virtual Services before starting your test. The scope of annotations are test methods.
This java annotation helps to embed your Virtual Services in your source code. This approach makes your application ready for Continous Integration testing by removing system and data constraints. **Your tests become more reliable, repeatable and automated**.
With this approach, using virtual services from your Continuous Integration plateform becomes native. 

== Projects description
- **devtest-unit-test-java** : Source code of the java api wrapped on **CA Devtest Rest API** to build and deploy virtual services
- **devtest-unit-test-java-annotation** : Source code of java annotations and Junit Rules used to parse our annotations
- **lisabank-demo** : Demo project using SV as Code annotation to deploy virtual services in junit test

== Installation

== Getting started
Here is a quick sample of how to use **" SV as code "** in your Junit classes:
[source,java,indent=0]
----	

/**
 * @author pascal.gasp@ca.com
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = LisaBankClientApplication.class)
@DevTestVirtualServer(registryHost = "localhost", deployServiceToVse = "VSE")

public class SimpleDemo {
	static final Log logger = LogFactory.getLog(SimpleDemo.class);
	@Autowired
	private BankService bankServices;
	@Rule
	public VirtualServicesRule rules = new VirtualServicesRule();

	@DevTestVirtualService(serviceName = "UserServiceTest-EJB3UserControlBean",
			port = 9080, basePath = "/itkoExamples/EJB3UserControlBean",
			rrpairsFolder = "UserServiceTest/getListUser/EJB3UserControlBean", 
			requestDataProtocol = {@Protocol(ProtocolType.DPH_SOAP) })
	@Test
	public void getListUser() {
		User[] users = bankServices.getListUser();
		assertNotNull(users);
		assertEquals(9, users.length);
	}
}


----	
This below annotation flag your Junit class as a Test using CA Virtual Services. This annotation will be used to refer to the CA DevTest Server :

* *registryHost* :* Registry hostname _(default value localhost)_
* *deployServiceToVse :* Name of VSE
* *login :* CA Devtest username _(default value svpower)_
* *password :* CA Devtest password _(default value svpower)_
 
[source,java,indent=0]
----	
@DevTestVirtualServer(registryHost = "localhost", deployServiceToVse = "VSE")
----
 

== Contributors

- Pascal Gasp *Sr Architect Devops @ CA Technologies*
- Vincent Mazot *Sr Consultant Devops @ CA Technologies*
- Olivier Laplace  *Sr Presales Devops @ CA Technologies*


