## CA SV As Code

This project provides simple **Java annotations** that can be used  in your Junit Test to deploy Virtual Services before starting your test. The scope of annotations are test methods.
This java annotation helps to embed your Virtual Services in your source code. This approach makes your application ready for continous integration testing by removing system and data constraints. **Your tests become more reliable, repeatable and automated**.
With this approach, using virtual services from your Continuous intergration plateform becomes native. 

## Projects descriptions
- **devtest-unit-test-java** : *Source code of the java api wrapped on **CA Devtest Rest API** to build and deploy virtual services*
- **devtest-unit-test-java-annotation** : *Source code of java annotations and Junit Rules used to parse our annotations*
- **lisabank-demo** : *Demo project using with junit test using annotation to deploy virtual services*

## Installation
TODO

## Code Example

[source,java,indent=0]
----	
package com.ca.devtest.lisabank.demo.sv.http;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.junit.Rule;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.ca.devtest.lisabank.demo.LisaBankClientApplication;
import com.ca.devtest.lisabank.demo.business.BankService;
import com.ca.devtest.lisabank.wsdl.User;
import com.ca.devtest.sv.devtools.annotation.DevTestVirtualServer;
import com.ca.devtest.sv.devtools.annotation.DevTestVirtualService;
import com.ca.devtest.sv.devtools.annotation.Protocol;
import com.ca.devtest.sv.devtools.annotation.ProtocolType;
import com.ca.devtest.sv.devtools.junit.VirtualServicesRule;

/**
 * @author pascal.gasp@ca.com
 *
 */
@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = LisaBankClientApplication.class)
@DevTestVirtualServer(registryHost="localhost" , deployServiceToVse = "VSE")

public class SimpleDemo {
	static final Log logger=LogFactory.getLog(SimpleDemo.class);
	@Autowired
	private BankService bankServices;
	@Rule
	public VirtualServicesRule rules = new VirtualServicesRule();
	
	@DevTestVirtualService(serviceName = "UserServiceTest-EJB3UserControlBean", 
			port = 9080, basePath = "/itkoExamples/EJB3UserControlBean",
			rrpairsFolder = "UserServiceTest/getListUser/EJB3UserControlBean", 
			requestDataProtocol = {@Protocol(ProtocolType.DPH_SOAP) })
	@Test
	public void getListUser() {
		User[] users = bankServices.getListUser();
		assertNotNull(users);
		assertEquals(9, users.length);

	}
	

}

----	

## Installation

TODO


## Contributors

- Pascal Gasp *Sr Architect Devops @ CA Technologies*
- Vincent Mazot *Sr Consultant Devops @ CA Technologies*
- Olivier Laplace  *Sr Presales Devops @ CA Technologies*

## License

TODO
